title: Nechceme zbytečné potraty
baseURL: https://cranky-brattain-9738bc.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139167009-1


menu:
  main:
    - name: Domů
      url: /
      weight: 10
    - name: Články
      identifier: post
      url: /post/
      weight: 20

params:
  description: Máš i jinou možnost.
  authors: Veronika, Vojta a Lubo

