title: Kondenzované kokosové mléko
baseURL: https://cranky-brattain-9738bc.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

