title: Nechceme zbytečné potraty
baseURL: https://cranky-brattain-9738bc.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139167009-1


menu:
  main:
    - name: Domovská stránka
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Zkus to jinak.
  authors: Authors

